BeeFocus: NetInterface Class Reference
NetInterface Class Reference abstract
Interface to the client.
#include <net_interface.h>
Public Member Functions
NetInterface ()
~NetInterface ()
virtual void setup (DebugInterface &debugLog)=0
virtual bool getString (WifiDebugOstream &log, std::string &string)=0
virtual NetInterface & operator<< (char c)=0
Detailed Description
Interface to the client.
This class's one job is to provide an interface to the client.
Definition at line 15 of file net_interface.h.
Constructor & Destructor Documentation
NetInterface()
NetInterface::NetInterface () inline
Definition at line 18 of file net_interface.h.
~NetInterface()
NetInterface::~NetInterface () inline
Definition at line 21 of file net_interface.h.
References getString(), operator<<(), and setup().
Member Function Documentation
getString()
virtual bool NetInterface::getString (WifiDebugOstream & log, std::string & string) pure virtual
Implemented in NetMockSimpleTimed, WifiInterfaceEthernet, and NetInterfaceSim.
Referenced by CommandParser::checkForCommands(), NetConnection::operator<<(), and ~NetInterface().
operator<<()
virtual NetInterface& NetInterface::operator<< (char c) pure virtual
Implemented in NetMockSimpleTimed, WifiInterfaceEthernet, and NetInterfaceSim.
Referenced by ~NetInterface().
setup()
virtual void NetInterface::setup (DebugInterface & debugLog) pure virtual
Implemented in WifiInterfaceEthernet, NetMockSimpleTimed, and NetInterfaceSim.
Referenced by ~NetInterface().
The documentation for this class was generated from the following file:
/home/andrew/src/beefocus_gh/firmware/net_interface.h