BeeFocus: FS::TimingParams Class Reference
FS::TimingParams Class Reference
#include <focuser_state.h>
Public Member Functions
TimingParams (int msEpochBetweenCommandChecksRHS=100, int maxStepsBetweenChecksRHS=50, unsigned msInactivityToSleepRHS=5 *60 *1000, int msEpochForSleepCommandChecksRHS=1 *1000, int msToPowerStepperRHS=1 *1000)
int getEpochBetweenCommandChecks () const
int getMaxStepsBetweenChecks () const
unsigned getInactivityToSleep () const
int getEpochForSleepCommandChecks () const
int getTimeToPowerStepper () const
Private Attributes
int msEpochBetweenCommandChecks
int maxStepsBetweenChecks
unsigned msInactivityToSleep
int msEpochForSleepCommandChecks
int msToPowerStepper
Detailed Description
Definition at line 116 of file focuser_state.h.
Constructor & Destructor Documentation
TimingParams()
FS::TimingParams::TimingParams (int msEpochBetweenCommandChecksRHS = 100, int maxStepsBetweenChecksRHS = 50, unsigned msInactivityToSleepRHS = 5*60*1000, int msEpochForSleepCommandChecksRHS = 1*1000, int msToPowerStepperRHS = 1*1000) inline
Definition at line 120 of file focuser_state.h.
Member Function Documentation
getEpochBetweenCommandChecks()
int FS::TimingParams::getEpochBetweenCommandChecks () const inline
Definition at line 135 of file focuser_state.h.
Referenced by FS::Focuser::stateAcceptCommands().
getEpochForSleepCommandChecks()
int FS::TimingParams::getEpochForSleepCommandChecks () const inline
Definition at line 147 of file focuser_state.h.
Referenced by FS::Focuser::stateSleep().
getInactivityToSleep()
unsigned FS::TimingParams::getInactivityToSleep () const inline
Definition at line 143 of file focuser_state.h.
Referenced by FS::Focuser::stateAcceptCommands().
getMaxStepsBetweenChecks()
int FS::TimingParams::getMaxStepsBetweenChecks () const inline
Definition at line 139 of file focuser_state.h.
Referenced by FS::Focuser::stateMoving(), and FS::Focuser::stateStopAtHome().
getTimeToPowerStepper()
int FS::TimingParams::getTimeToPowerStepper () const inline
Definition at line 151 of file focuser_state.h.
Referenced by FS::Focuser::stateSleep().
Member Data Documentation
maxStepsBetweenChecks
int FS::TimingParams::maxStepsBetweenChecks private
Definition at line 158 of file focuser_state.h.
msEpochBetweenCommandChecks
int FS::TimingParams::msEpochBetweenCommandChecks private
Definition at line 157 of file focuser_state.h.
msEpochForSleepCommandChecks
int FS::TimingParams::msEpochForSleepCommandChecks private
Definition at line 160 of file focuser_state.h.
msInactivityToSleep
unsigned FS::TimingParams::msInactivityToSleep private
Definition at line 159 of file focuser_state.h.
msToPowerStepper
int FS::TimingParams::msToPowerStepper private
Definition at line 161 of file focuser_state.h.
The documentation for this class was generated from the following file:
/home/andrew/src/beefocus_gh/firmware/focuser_state.h