var annotated_dup =
[
    [ "CommandParser", "df/d0c/namespace_command_parser.html", "df/d0c/namespace_command_parser" ],
    [ "DebugESP8266", "d1/d72/class_debug_e_s_p8266.html", "d1/d72/class_debug_e_s_p8266" ],
    [ "DebugInterface", "dd/d7d/class_debug_interface.html", "dd/d7d/class_debug_interface" ],
    [ "DebugInterfaceIgnoreMock", "da/d43/class_debug_interface_ignore_mock.html", "da/d43/class_debug_interface_ignore_mock" ],
    [ "DebugInterfaceSim", "d9/d91/class_debug_interface_sim.html", "d9/d91/class_debug_interface_sim" ],
    [ "EnumHash", "d0/d34/struct_enum_hash.html", "d0/d34/struct_enum_hash" ],
    [ "FocuserState", "d0/d0e/class_focuser_state.html", "d0/d0e/class_focuser_state" ],
    [ "HardwareESP8266", "df/dff/class_hardware_e_s_p8266.html", "df/dff/class_hardware_e_s_p8266" ],
    [ "HWEvent", "d1/d2c/class_h_w_event.html", "d1/d2c/class_h_w_event" ],
    [ "HWI", "d3/de6/class_h_w_i.html", "d3/de6/class_h_w_i" ],
    [ "HWISim", "d4/d99/class_h_w_i_sim.html", "d4/d99/class_h_w_i_sim" ],
    [ "HWMockTimed", "df/ddc/class_h_w_mock_timed.html", "df/ddc/class_h_w_mock_timed" ],
    [ "is_beefocus_ostream", "d7/d85/structis__beefocus__ostream.html", null ],
    [ "is_beefocus_ostream< DebugInterface >", "dd/d2b/structis__beefocus__ostream_3_01_debug_interface_01_4.html", null ],
    [ "is_beefocus_ostream< NetInterface >", "d2/d15/structis__beefocus__ostream_3_01_net_interface_01_4.html", null ],
    [ "is_beefocus_ostream< WifiConnectionEthernet >", "d7/d8a/structis__beefocus__ostream_3_01_wifi_connection_ethernet_01_4.html", null ],
    [ "is_beefocus_ostream< WifiDebugOstream >", "db/d53/structis__beefocus__ostream_3_01_wifi_debug_ostream_01_4.html", null ],
    [ "NetConnection", "d0/dfb/class_net_connection.html", "d0/dfb/class_net_connection" ],
    [ "NetInterface", "d8/d66/class_net_interface.html", "d8/d66/class_net_interface" ],
    [ "NetInterfaceSim", "d5/dc6/class_net_interface_sim.html", "d5/dc6/class_net_interface_sim" ],
    [ "NetMockSimpleTimed", "d5/d11/class_net_mock_simple_timed.html", "d5/d11/class_net_mock_simple_timed" ],
    [ "TimedEvent", "dd/dee/class_timed_event.html", "dd/dee/class_timed_event" ],
    [ "WifiConnectionEthernet", "d2/df5/class_wifi_connection_ethernet.html", "d2/df5/class_wifi_connection_ethernet" ],
    [ "WifiDebugOstream", "da/d81/class_wifi_debug_ostream.html", "da/d81/class_wifi_debug_ostream" ],
    [ "WifiInterfaceEthernet", "df/d42/class_wifi_interface_ethernet.html", "df/d42/class_wifi_interface_ethernet" ],
    [ "WifiOstream", "d4/d86/class_wifi_ostream.html", "d4/d86/class_wifi_ostream" ]
];