BeeFocus: HWEvent Class Reference
HWEvent Class Reference
a Hardware Event
#include <test_mock_event.h>
Public Member Functions
HWEvent ()=delete
Default Constructor (deleted)
HWEvent (HWI::Pin pinRHS, HWI::PinState stateRHS)
Constructor for Pin IO Read or Write event.
HWEvent (HWI::Pin pinRHS, HWI::PinIOMode modeRHS)
Constructor for setting a pin's GPIO to an input or output.
bool operator== (const HWEvent &rhs) const
Equality operator.
bool isIO () const
Is the event an IO read or write event.
bool isMode () const
Is the event a set GPIO mode to Input or Output event.
HWI::PinState getIO () const
Get the new state for an IO read or write event.
HWI::PinIOMode getMode () const
Get the new mode for a set GPIO mode event.
HWI::Pin getPin () const
Get the pin.
Private Types
enum Type { Type::DIGITAL_IO, Type::PIN_MODE }
Private Attributes
HWI::Pin pin
Type type
union {
HWI::PinState state
HWI::PinIOMode mode
};
Detailed Description
a Hardware Event
Hardware events present a change of some kind in to the hardware interface. They're used to either mock events in a test, like the home switch activating, or to describe events that we expec to occur, like the stepper motor pin being asked to go in reverse.
Examples:
Event : HWEvent(HWI::Pin::DIR, HWI::PinState::Dir_FIRWARD) Meaning : The stepper motor direction pin is set to "go forward"
Event : HWEvent(HWI::Pin::DIR, HWI::PinIOMode::M_OUTPUT) Meaning : The stepper motor direction GPIO is set to output mode
Event : HWEvent(HWI::Pin::HOME, HWI::PinIOMode::M_INPUT) Meaning : The stepper motor home GPIO is set to input mode
Event : HWEvent(HWI::Pin::HOME, HWI::PinState::HOME_ACTIVE) Meaning : The home pin's input is now active (i.e., the focuser is in the home position & the home switch was activated).
Definition at line 31 of file test_mock_event.h.
Member Enumeration Documentation
Type
enum HWEvent::Type strong private
Enumerator
DIGITAL_IO
PIN_MODE
Definition at line 102 of file test_mock_event.h.
Constructor & Destructor Documentation
HWEvent() [1/3]
HWEvent::HWEvent () delete
Default Constructor (deleted)
HWEvent() [2/3]
HWEvent::HWEvent (HWI::Pin pinRHS, HWI::PinState stateRHS) inline
Constructor for Pin IO Read or Write event.
Parameters
[in] The pin that the read or write takes place on
[in] The new pin state.
Definition at line 46 of file test_mock_event.h.
References DIGITAL_IO, state, and type.
HWEvent() [3/3]
HWEvent::HWEvent (HWI::Pin pinRHS, HWI::PinIOMode modeRHS) inline
Constructor for setting a pin's GPIO to an input or output.
Parameters
[in] The pin that we're setting the GPIO mode on
[in] The new mode (i.e., output or input)
Definition at line 59 of file test_mock_event.h.
References mode, PIN_MODE, and type.
Member Function Documentation
getIO()
HWI::PinState HWEvent::getIO () const inline
Get the new state for an IO read or write event.
Definition at line 84 of file test_mock_event.h.
References isIO(), and state.
Referenced by operator<<().
getMode()
HWI::PinIOMode HWEvent::getMode () const inline
Get the new mode for a set GPIO mode event.
Definition at line 91 of file test_mock_event.h.
References isMode(), and mode.
Referenced by operator<<().
getPin()
HWI::Pin HWEvent::getPin () const inline
Get the pin.
Definition at line 98 of file test_mock_event.h.
References pin.
Referenced by operator<<().
isIO()
bool HWEvent::isIO () const inline
Is the event an IO read or write event.
Definition at line 78 of file test_mock_event.h.
References DIGITAL_IO, and type.
Referenced by getIO(), and operator<<().
isMode()
bool HWEvent::isMode () const inline
Is the event a set GPIO mode to Input or Output event.
Definition at line 81 of file test_mock_event.h.
References PIN_MODE, and type.
Referenced by getMode().
operator==()
bool HWEvent::operator== (const HWEvent & rhs) const inline
Equality operator.
Parameters
[in] rhs = The other event to compare to
Definition at line 70 of file test_mock_event.h.
References DIGITAL_IO, mode, pin, state, and type.
Member Data Documentation
@3
union { ... }
mode
HWI::PinIOMode HWEvent::mode
Definition at line 113 of file test_mock_event.h.
Referenced by getMode(), HWEvent(), and operator==().
pin
HWI::Pin HWEvent::pin private
Definition at line 108 of file test_mock_event.h.
Referenced by getPin(), and operator==().
state
HWI::PinState HWEvent::state
Definition at line 112 of file test_mock_event.h.
Referenced by getIO(), HWEvent(), and operator==().
type
Type HWEvent::type private
Definition at line 109 of file test_mock_event.h.
Referenced by HWEvent(), isIO(), isMode(), and operator==().
The documentation for this class was generated from the following file:
/home/andrew/src/beefocus_gh/unit_tests/test_mock_event.h