BeeFocus: FocuserState Class Reference
FocuserState Class Reference
#include <focuser_state.h>
Classes
class COMMAND_PACKET
Public Types
enum State {
State::START_OF_STATES = 0, State::ACCEPT_COMMANDS = 0, State::DO_STEPS, State::STEPPER_INACTIVE_AND_WAIT,
State::STEPPER_ACTIVE_AND_WAIT, State::SET_DIR, State::MOVING, State::STOP_AT_HOME,
State::LOW_POWER, State::AWAKEN, State::ERROR_STATE, State::END_OF_STATES
}
Focuser's State Enum.
using ptrToMember = unsigned int(FocuserState::*)(void)
Public Member Functions
FocuserState (std::unique_ptr< NetInterface > netArg, std::unique_ptr< HWI > hardwareArg, std::unique_ptr< DebugInterface > debugArg)
Focuser State Constructor.
FocuserState (const FocuserState &other)=delete
Deleted copy constructor.
FocuserState ()=delete
Deleted default constructor.
FocuserState & operator= (const FocuserState &)=delete
Deleted assignment operator.
unsigned int loop ()
Update the Focuser's State.
Static Public Attributes
static const std::unordered_map< State, const std::string, EnumHash > stateNames
Debug names for each state.
static const std::unordered_map< CommandParser::Command, bool, EnumHash > doesCommandInterrupt
Does a particular incoming command interrupt the current state.
static const std::unordered_map< State, ptrToMember, EnumHash > stateImpl
Private Types
enum Dir { Dir::FORWARD, Dir::REVERSE }
enum MotorState { MotorState::ON, MotorState::OFF }
Private Member Functions
void hard_reset_state (State, int argument)
void pushState (State new_state, int arg0=-1)
void processCommand (CommandParser::CommandPacket cp)
unsigned int stateAcceptCommands (void)
Wait for commands from the network interface.
unsigned int stateMoving (void)
Move to position.
unsigned int stateDoingSteps (void)
Move the stepper.
unsigned int stateSetDir (void)
If needed, Change the state of the direction pin and pause.
unsigned int stateStepActiveAndWait (void)
Set the Stepper to active (i.e., start step) and wait.
unsigned int stateStepInactiveAndWait (void)
Set the Stepper to inactive (i.e., finish step) and wait.
unsigned int state_check_for_abort (void)
unsigned int state_stop_at_home (void)
unsigned int state_low_power (void)
unsigned int state_awaken (void)
unsigned int stateError (void)
COMMAND_PACKET & top (void)
Private Attributes
std::unique_ptr< NetInterface > net
std::unique_ptr< HWI > hardware
std::unique_ptr< DebugInterface > debugLog
Dir dir
What direction are we going?
MotorState motorState
Is the Stepper Motor On or Off.
int focuserPosition
What is the focuser's position of record.
std::vector< COMMAND_PACKET > stateStack
The focuser's state.
Detailed Description
Definition at line 12 of file focuser_state.h.
Member Typedef Documentation
ptrToMember
using FocuserState::ptrToMember = unsigned int (FocuserState::*) (void)
Definition at line 75 of file focuser_state.h.
Member Enumeration Documentation
Dir
enum FocuserState::Dir strong private
Enumerator
FORWARD
REVERSE
Definition at line 117 of file focuser_state.h.
MotorState
enum FocuserState::MotorState strong private
Enumerator
ON
OFF
Definition at line 129 of file focuser_state.h.
State
enum FocuserState::State strong
Focuser's State Enum.
TODO - describe state machine operation in one place, probably in the FocuserState class description
Enumerator
START_OF_STATES
ACCEPT_COMMANDS
DO_STEPS
STEPPER_INACTIVE_AND_WAIT
STEPPER_ACTIVE_AND_WAIT
SET_DIR
MOVING
STOP_AT_HOME
LOW_POWER
AWAKEN
ERROR_STATE
END_OF_STATES
Definition at line 48 of file focuser_state.h.
Constructor & Destructor Documentation
FocuserState() [1/3]
FocuserState::FocuserState (std::unique_ptr< NetInterface > netArg, std::unique_ptr< HWI > hardwareArg, std::unique_ptr< DebugInterface > debugArg)
Focuser State Constructor.
Parameters
[in] netArg - Interface to the network
[in] hardwareArg - Interface to the Hardware
[in] debugArg - Interface to the debug logger.
Definition at line 55 of file focuser_state.cpp.
References ACCEPT_COMMANDS, debugLog, HWI::DIR, dir, HWI::DIR_FORWARD, focuserPosition, FORWARD, hard_reset_state(), hardware, HWI::HOME, HWI::M_INPUT, HWI::M_OUTPUT, HWI::MOTOR_ENA, HWI::MOTOR_ON, motorState, net, ON, HWI::STEP, and HWI::STEP_INACTIVE.
FocuserState() [2/3]
FocuserState::FocuserState (const FocuserState & other) delete
Deleted copy constructor.
FocuserState() [3/3]
FocuserState::FocuserState () delete
Deleted default constructor.
Member Function Documentation
hard_reset_state()
void FocuserState::hard_reset_state (State new_state, int argument) private
Definition at line 99 of file focuser_state.cpp.
References stateStack.
Referenced by FocuserState(), processCommand(), and top().
loop()
unsigned int FocuserState::loop (void)
Update the Focuser's State.
Returns
The amount of time the caller should wait (in microsecodns) before calling loop again.
Definition at line 334 of file focuser_state.cpp.
References stateImpl, and top().
Referenced by simulateFocuser().
operator=()
FocuserState& FocuserState::operator= (const FocuserState &) delete
Deleted assignment operator.
processCommand()
void FocuserState::processCommand (CommandParser::CommandPacket cp) private
Definition at line 118 of file focuser_state.cpp.
References CommandParser::Abort, CommandParser::ABSPos, ACCEPT_COMMANDS, FocuserState::COMMAND_PACKET::arg0, AWAKEN, CommandParser::CommandPacket::command, debugLog, focuserPosition, hard_reset_state(), CommandParser::Home, LOW_POWER, MOVING, net, CommandParser::CommandPacket::optionalArg, CommandParser::PStatus, pushState(), CommandParser::Sleep, CommandParser::SStatus, FocuserState::COMMAND_PACKET::state, stateNames, CommandParser::Status, STOP_AT_HOME, top(), and CommandParser::Wake.
Referenced by state_low_power(), and stateAcceptCommands().
pushState()
void FocuserState::pushState (State new_state, int arg0 = -1) private
Definition at line 106 of file focuser_state.cpp.
References stateStack.
Referenced by processCommand(), state_stop_at_home(), stateDoingSteps(), and stateMoving().
state_awaken()
unsigned int FocuserState::state_awaken (void) private
Definition at line 320 of file focuser_state.cpp.
References hardware, HWI::MOTOR_ENA, HWI::MOTOR_ON, and stateStack.
state_check_for_abort()
unsigned int FocuserState::state_check_for_abort (void) private
state_low_power()
unsigned int FocuserState::state_low_power (void) private
Definition at line 199 of file focuser_state.cpp.
References CommandParser::checkForCommands(), debugLog, hardware, HWI::MOTOR_ENA, HWI::MOTOR_OFF, motorState, net, CommandParser::NoCommand, OFF, and processCommand().
state_stop_at_home()
unsigned int FocuserState::state_stop_at_home (void) private
Definition at line 298 of file focuser_state.cpp.
References debugLog, DO_STEPS, focuserPosition, hardware, HWI::HOME, HWI::HOME_ACTIVE, net, pushState(), SET_DIR, and stateStack.
stateAcceptCommands()
unsigned int FocuserState::stateAcceptCommands (void) private
Wait for commands from the network interface.
Definition at line 186 of file focuser_state.cpp.
References CommandParser::checkForCommands(), debugLog, net, CommandParser::NoCommand, and processCommand().
stateDoingSteps()
unsigned int FocuserState::stateDoingSteps (void) private
Move the stepper.
steps
Definition at line 253 of file focuser_state.cpp.
References FocuserState::COMMAND_PACKET::arg0, dir, focuserPosition, FORWARD, pushState(), stateStack, STEPPER_ACTIVE_AND_WAIT, STEPPER_INACTIVE_AND_WAIT, and top().
stateError()
unsigned int FocuserState::stateError (void) private
Definition at line 327 of file focuser_state.cpp.
References debugLog, and net.
stateMoving()
unsigned int FocuserState::stateMoving (void) private
Move to position.
Definition at line 271 of file focuser_state.cpp.
References FocuserState::COMMAND_PACKET::arg0, debugLog, DO_STEPS, focuserPosition, hardware, HWI::MOTOR_ENA, HWI::MOTOR_ON, motorState, net, ON, pushState(), SET_DIR, stateStack, and top().
stateSetDir()
unsigned int FocuserState::stateSetDir (void) private
If needed, Change the state of the direction pin and pause.
Definition at line 218 of file focuser_state.cpp.
References FocuserState::COMMAND_PACKET::arg0, HWI::DIR, dir, HWI::DIR_BACKWARD, HWI::DIR_FORWARD, FORWARD, hardware, REVERSE, stateStack, and top().
stateStepActiveAndWait()
unsigned int FocuserState::stateStepActiveAndWait (void) private
Set the Stepper to active (i.e., start step) and wait.
Definition at line 246 of file focuser_state.cpp.
References hardware, stateStack, HWI::STEP, and HWI::STEP_ACTIVE.
stateStepInactiveAndWait()
unsigned int FocuserState::stateStepInactiveAndWait (void) private
Set the Stepper to inactive (i.e., finish step) and wait.
Definition at line 239 of file focuser_state.cpp.
References hardware, stateStack, HWI::STEP, and HWI::STEP_INACTIVE.
top()
FocuserState::COMMAND_PACKET & FocuserState::top (void) private
Definition at line 111 of file focuser_state.cpp.
References ERROR_STATE, hard_reset_state(), and stateStack.
Referenced by loop(), processCommand(), stateDoingSteps(), stateMoving(), and stateSetDir().
Member Data Documentation
debugLog
std::unique_ptr<DebugInterface> FocuserState::debugLog private
Definition at line 115 of file focuser_state.h.
Referenced by FocuserState(), processCommand(), state_low_power(), state_stop_at_home(), stateAcceptCommands(), stateError(), and stateMoving().
dir
Dir FocuserState::dir private
What direction are we going?
FORWARD = counting up. REVERSE = counting down.
Definition at line 127 of file focuser_state.h.
Referenced by FocuserState(), stateDoingSteps(), and stateSetDir().
doesCommandInterrupt
const std::unordered_map< CommandParser::Command, bool, EnumHash > FocuserState::doesCommandInterrupt static
Initial value:
=
{
  { CommandParser::Command::Ping,          false  },
  { CommandParser::Command::Abort,         true   },
  { CommandParser::Command::Home,          true   },
  { CommandParser::Command::Status,        false  },
  { CommandParser::Command::PStatus,       false  },
  { CommandParser::Command::SStatus,       false  },
  { CommandParser::Command::ABSPos,        true   },
  { CommandParser::Command::Sleep,         true   },
  { CommandParser::Command::Wake,          true   },
  { CommandParser::Command::NoCommand,     false  },
}
Does a particular incoming command interrupt the current state.
Example 1. A "Status" Command will not interrupt a move sequence Example 2. A "Home" Command will interrupt a focuser's move sequence
Definition at line 73 of file focuser_state.h.
Referenced by TEST().
focuserPosition
int FocuserState::focuserPosition private
What is the focuser's position of record.
Definition at line 138 of file focuser_state.h.
Referenced by FocuserState(), processCommand(), state_stop_at_home(), stateDoingSteps(), and stateMoving().
hardware
std::unique_ptr<HWI> FocuserState::hardware private
Definition at line 114 of file focuser_state.h.
Referenced by FocuserState(), state_awaken(), state_low_power(), state_stop_at_home(), stateMoving(), stateSetDir(), stateStepActiveAndWait(), and stateStepInactiveAndWait().
motorState
MotorState FocuserState::motorState private
Is the Stepper Motor On or Off.
Definition at line 135 of file focuser_state.h.
Referenced by FocuserState(), state_low_power(), and stateMoving().
net
std::unique_ptr<NetInterface> FocuserState::net private
Definition at line 113 of file focuser_state.h.
Referenced by FocuserState(), processCommand(), state_low_power(), state_stop_at_home(), stateAcceptCommands(), stateError(), and stateMoving().
stateImpl
const std::unordered_map< FocuserState::State, unsigned int(FocuserState::*)(void), EnumHash > FocuserState::stateImpl static
Initial value:
=
{
  { State::ACCEPT_COMMANDS,           &FocuserState::stateAcceptCommands },
  { State::DO_STEPS,                  &FocuserState::stateDoingSteps },
  { State::STEPPER_INACTIVE_AND_WAIT, &FocuserState::stateStepInactiveAndWait },
  { State::STEPPER_ACTIVE_AND_WAIT,   &FocuserState::stateStepActiveAndWait },
  { State::SET_DIR,                   &FocuserState::stateSetDir },
  { State::MOVING,                    &FocuserState::stateMoving },
  { State::STOP_AT_HOME,              &FocuserState::state_stop_at_home },
  { State::LOW_POWER,                 &FocuserState::state_low_power },
  { State::AWAKEN,                    &FocuserState::state_awaken },
  { State::ERROR_STATE,               &FocuserState::stateError }
}
Definition at line 77 of file focuser_state.h.
Referenced by loop(), and TEST().
stateNames
const std::unordered_map< FocuserState::State, const std::string, EnumHash > FocuserState::stateNames static
Initial value:
=
{
  { State::ACCEPT_COMMANDS,               "ACCEPTING_COMMANDS" },
  { State::DO_STEPS,                      "DO_STEPS"           },
  { State::STEPPER_INACTIVE_AND_WAIT,     "STEPPER_INACTIVE"   },
  { State::STEPPER_ACTIVE_AND_WAIT,       "STEPPER_ACTIVE"     },
  { State::SET_DIR,                       "SET_DIR"            },
  { State::MOVING,                        "MOVING"             },
  { State::STOP_AT_HOME,                  "STOP_AT_HOME"       },
  { State::LOW_POWER,                     "LOW_POWER"          },
  { State::AWAKEN,                        "AWAKEN"             },
  { State::ERROR_STATE,                   "ERROR ERROR ERROR"  },
}
Debug names for each state.
Definition at line 64 of file focuser_state.h.
Referenced by processCommand(), and TEST().
stateStack
std::vector< COMMAND_PACKET > FocuserState::stateStack private
The focuser's state.
Definition at line 141 of file focuser_state.h.
Referenced by hard_reset_state(), pushState(), state_awaken(), state_stop_at_home(), stateDoingSteps(), stateMoving(), stateSetDir(), stateStepActiveAndWait(), stateStepInactiveAndWait(), and top().
The documentation for this class was generated from the following files:
/home/andrew/src/beefocus/firmware/focuser_state.h
/home/andrew/src/beefocus/firmware/focuser_state.cpp