BeeFocus: FS::StateArg Class Reference
FS::StateArg Class Reference
#include <focuser_state.h>
Public Types
enum Type { Type::NONE, Type::INT, Type::DIR }
Public Member Functions
StateArg ()
StateArg (int i)
StateArg (Dir d)
Type getType ()
int getInt ()
Dir getDir ()
Private Attributes
Type type
union {
int intArg
Dir dirArg
};
Detailed Description
Definition at line 89 of file focuser_state.h.
Member Enumeration Documentation
Type
enum FS::StateArg::Type strong
Enumerator
NONE
INT
DIR
Definition at line 93 of file focuser_state.h.
Constructor & Destructor Documentation
StateArg() [1/3]
FS::StateArg::StateArg () inline
Definition at line 99 of file focuser_state.h.
StateArg() [2/3]
FS::StateArg::StateArg (int i) inline
Definition at line 100 of file focuser_state.h.
StateArg() [3/3]
FS::StateArg::StateArg (Dir d) inline
Definition at line 101 of file focuser_state.h.
Member Function Documentation
getDir()
Dir FS::StateArg::getDir () inline
Definition at line 104 of file focuser_state.h.
Referenced by FS::Focuser::stateSetDir().
getInt()
int FS::StateArg::getInt () inline
Definition at line 103 of file focuser_state.h.
Referenced by FS::operator<<(), FS::Focuser::stateDoingSteps(), and FS::Focuser::stateMoving().
getType()
Type FS::StateArg::getType () inline
Definition at line 102 of file focuser_state.h.
Referenced by FS::operator<<().
Member Data Documentation
@1
union { ... }
dirArg
Dir FS::StateArg::dirArg
Definition at line 112 of file focuser_state.h.
intArg
int FS::StateArg::intArg
Definition at line 111 of file focuser_state.h.
type
Type FS::StateArg::type private
Definition at line 108 of file focuser_state.h.
The documentation for this class was generated from the following file:
/home/andrew/src/beefocus_gh/firmware/focuser_state.h