BeeFocus: CommandParser Namespace Reference
CommandParser Namespace Reference
Classes
class CommandPacket
class CommandTemplate
The Template for a bee-focuser command.
Enumerations
enum HasArg { HasArg::Yes, HasArg::No }
enum Command {
Command::StartOfCommands = 0, Command::Abort = 0, Command::Home, Command::PStatus,
Command::SStatus, Command::HStatus, Command::ABSPos, Command::NoCommand,
Command::EndOfCommands
}
Functions
int process_int (const std::string &string, size_t pos)
Process an integer argument.
const CommandPacket checkForCommands (DebugInterface &log, NetInterface &netInterface)
Get commands from the network interface.
TEST (COMMAND_PARSER, should_process_int)
TEST (COMMAND_PARSER, checkForCommands)
TEST (COMMAND_PARSER, testGot)
Variables
const std::vector< CommandTemplate > commandTemplates
constexpr int NoArg = -1
Enumeration Type Documentation
Command
enum CommandParser::Command strong
Enumerator
StartOfCommands
Start of the command list.
Abort
Abort a move.
Home
Rewind until the home pin is active.
PStatus
Return Position to Caller.
SStatus
Return the State (i.e., "moving", "homing")
HStatus
Return Home Status (i.e, "homed" or "!homed")
ABSPos
Move to an absolute position.
NoCommand
No command was specified.
EndOfCommands
End of the comand list.
Definition at line 14 of file command_parser.h.
HasArg
enum CommandParser::HasArg strong
Enumerator
Yes
No
Definition at line 11 of file command_parser.cpp.
Function Documentation
checkForCommands()
const CommandPacket CommandParser::checkForCommands (DebugInterface & log, NetInterface & netInterface)
Get commands from the network interface.
Parameters
[in] log - Debug Log stream
[in] netInterface - The network interface that we'll query for the command.
Returns
New requests from netInterface that need to be acted on.
TODO
Error handling (has none).
Move extra parameters used by the STATUS command.
Definition at line 66 of file command_parser.cpp.
References CommandParser::CommandPacket::command, NetInterface::getString(), CommandParser::CommandPacket::optionalArg, process_int(), and Yes.
Referenced by FS::Focuser::stateAcceptCommands(), FS::Focuser::stateMoving(), FS::Focuser::stateSleep(), FS::Focuser::stateStopAtHome(), and TEST().
process_int()
int CommandParser::process_int (const std::string & string, size_t pos)
Process an integer argument.
Read an integer argument from a string in a way that's guaranteed not to allocate memory
Parameters
[in] string - The string
[in] pos - The start position in the string. i.e., if pos=5 we'll look for the number at string element 5.
Returns
- The result. Currently 0 if there's no number.
Definition at line 49 of file command_parser.cpp.
Referenced by checkForCommands(), and TEST().
TEST() [1/3]
CommandParser::TEST (COMMAND_PARSER , should_process_int)
Definition at line 12 of file test_check_for_commands.cpp.
References process_int().
TEST() [2/3]
CommandParser::TEST (COMMAND_PARSER , checkForCommands)
Definition at line 25 of file test_check_for_commands.cpp.
References Abort, ABSPos, checkForCommands(), Home, PStatus, and SStatus.
TEST() [3/3]
CommandParser::TEST (COMMAND_PARSER , testGot)
Definition at line 71 of file test_check_for_commands.cpp.
References Abort, ABSPos, NetMockSimpleTimed::advanceTime(), checkForCommands(), and NetMockSimpleTimed::getOutput().
Variable Documentation
commandTemplates
const std::vector<CommandTemplate> CommandParser::commandTemplates
Initial value:
=
{
  { "abort",      Command::Abort,    HasArg::No  },
  { "home",       Command::Home,     HasArg::No  },
  { "pstatus",    Command::PStatus,  HasArg::No  },
  { "sstatus",    Command::SStatus,  HasArg::No  },
  { "hstatus",    Command::HStatus,  HasArg::No  },
  { "abs_pos",    Command::ABSPos,   HasArg::Yes },
}
Definition at line 29 of file command_parser.cpp.
NoArg
constexpr int CommandParser::NoArg = -1
Definition at line 26 of file command_parser.h.