BeeFocus: WifiConnectionEthernet Class Reference
WifiConnectionEthernet Class Reference
#include <net_esp8266.h>
Public Member Functions
WifiConnectionEthernet ()
~WifiConnectionEthernet ()
void reset (void)
WifiConnectionEthernet & operator<< (char c)
void putchar (char c) override
void initConnection (WiFiServer &server)
bool getString (WifiDebugOstream &log, std::string &string) override
operator bool (void) override
Public Member Functions inherited from NetConnection
NetConnection & operator<< (char c)
Private Member Functions
void handleNewIncomingData (WifiDebugOstream &log)
Private Attributes
int m_currentIncomingBuffer
std::string m_incomingBuffers [2]
WiFiClient m_connectedClient
Additional Inherited Members
Detailed Description
Definition at line 14 of file net_esp8266.h.
Constructor & Destructor Documentation
WifiConnectionEthernet()
WifiConnectionEthernet::WifiConnectionEthernet () inline
Definition at line 18 of file net_esp8266.h.
References reset().
~WifiConnectionEthernet()
WifiConnectionEthernet::~WifiConnectionEthernet () inline
Definition at line 23 of file net_esp8266.h.
References reset().
Member Function Documentation
getString()
bool WifiConnectionEthernet::getString (WifiDebugOstream & log, std::string & string) override virtual
Implements NetConnection.
Definition at line 103 of file net_esp8266.cpp.
Referenced by putchar(), and WifiInterfaceEthernet::~WifiInterfaceEthernet().
handleNewIncomingData()
void WifiConnectionEthernet::handleNewIncomingData (WifiDebugOstream & log) private
Definition at line 127 of file net_esp8266.cpp.
Referenced by operator bool().
initConnection()
void WifiConnectionEthernet::initConnection (WiFiServer & server)
Definition at line 92 of file net_esp8266.cpp.
Referenced by putchar().
operator bool()
WifiConnectionEthernet::operator bool (void) inline override virtual
Implements NetConnection.
Definition at line 55 of file net_esp8266.h.
References handleNewIncomingData(), and m_connectedClient.
operator<<()
WifiConnectionEthernet& WifiConnectionEthernet::operator<< (char c) inline
Definition at line 39 of file net_esp8266.h.
References putchar().
Referenced by WifiInterfaceEthernet::~WifiInterfaceEthernet().
putchar()
void WifiConnectionEthernet::putchar (char c) inline override virtual
Implements NetConnection.
Definition at line 45 of file net_esp8266.h.
References getString(), initConnection(), and m_connectedClient.
Referenced by operator<<().
reset()
void WifiConnectionEthernet::reset (void) inline virtual
Implements NetConnection.
Definition at line 28 of file net_esp8266.h.
References m_connectedClient, m_currentIncomingBuffer, and m_incomingBuffers.
Referenced by WifiConnectionEthernet(), WifiInterfaceEthernet::WifiInterfaceEthernet(), ~WifiConnectionEthernet(), and WifiInterfaceEthernet::~WifiInterfaceEthernet().
Member Data Documentation
m_connectedClient
WiFiClient WifiConnectionEthernet::m_connectedClient private
Definition at line 65 of file net_esp8266.h.
Referenced by operator bool(), putchar(), and reset().
m_currentIncomingBuffer
int WifiConnectionEthernet::m_currentIncomingBuffer private
Definition at line 63 of file net_esp8266.h.
Referenced by reset().
m_incomingBuffers
std::string WifiConnectionEthernet::m_incomingBuffers[2] private
Definition at line 64 of file net_esp8266.h.
Referenced by reset().
The documentation for this class was generated from the following files:
/home/andrew/src/beefocus/firmware/net_esp8266.h
/home/andrew/src/beefocus/firmware/net_esp8266.cpp