BeeFocus: NetMockSimpleTimed Class Reference
NetMockSimpleTimed Class Reference
Testing Mock for network events.
#include <test_mock_net.h>
Public Member Functions
NetMockSimpleTimed (const TimedStringEvents &inputEventsArg)
Create a network mock given a vector of Input Events.
NetMockSimpleTimed (const char *string)
Create a simple network with 1 input event at time=0.
NetMockSimpleTimed ()
Create a simple network with no input events.
NetMockSimpleTimed (const HWMockTimed &)=delete
NetMockSimpleTimed & operator= (const NetMockSimpleTimed &)=delete
void setup (DebugInterface &debugLog) override
Implement setup required by NetInterface.
bool getString (WifiDebugOstream &log, std::string &returnString) override
Get input from the net interface.
NetInterface & operator<< (char c) override
Output a chacacter to the interface usign a streaming operator.
void advanceTime (int ticks)
Advance network mock time by "ticks" ms.
const TimedStringEvents & getOutput ()
Get output events for golden result comparison.
Public Member Functions inherited from NetInterface
NetInterface ()
~NetInterface ()
Private Attributes
int time
Current Time.
std::string currentOutput
The current string that's being written to.
TimedStringEvents outputEvents
Recorded output events.
const TimedStringEvents inputEvents
Input events to be sent back to the caller.
TimedStringEvents::const_iterator nextInputEvent
The next input event that needs to be processed.
Detailed Description
Testing Mock for network events.
Testing Mock for network events
NetMockSimpleTimed implements a mock Network Interface (NetInterface) that's used in unit testing. The class implements testing mocks for the interfaces required by the NetInterface class. In additiona to that, the class does the following:
Maintain Time. The class simulates the passage of time. advanceTime is called to "move" time forward
Record Output. Whenever a caller outputs a string to the network interface, the string and the time the string was outputted are recorded as an event. Tests can use this log to verify that the data being sent to the caller matches a golden result.
Simulate Input. On class construction, the caller can specify a series of input events and the time those events occur at. i.e., the caller can say 'at time 20ms the string "HOME" will arrive from the network'
Definition at line 32 of file test_mock_net.h.
Constructor & Destructor Documentation
NetMockSimpleTimed() [1/4]
NetMockSimpleTimed::NetMockSimpleTimed (const TimedStringEvents & inputEventsArg) inline
Create a network mock given a vector of Input Events.
Parameters
[in] inputEventsArg - Simulated input from the network interface. A vector of input strings and the time those strings arrive at.
Definition at line 43 of file test_mock_net.h.
References currentOutput, inputEvents, nextInputEvent, and time.
NetMockSimpleTimed() [2/4]
NetMockSimpleTimed::NetMockSimpleTimed (const char * string) inline
Create a simple network with 1 input event at time=0.
Parameters
[in] string - A C style string with the single input
Definition at line 56 of file test_mock_net.h.
References currentOutput, inputEvents, nextInputEvent, and time.
NetMockSimpleTimed() [3/4]
NetMockSimpleTimed::NetMockSimpleTimed () inline
Create a simple network with no input events.
Definition at line 67 of file test_mock_net.h.
References currentOutput, inputEvents, nextInputEvent, operator=(), and time.
NetMockSimpleTimed() [4/4]
NetMockSimpleTimed::NetMockSimpleTimed (const HWMockTimed &) delete
Member Function Documentation
advanceTime()
void NetMockSimpleTimed::advanceTime (int ticks) inline
Advance network mock time by "ticks" ms.
Parameters
[in] The amount of time by, in ms
Definition at line 145 of file test_mock_net.h.
References time.
Referenced by simulateFocuser(), and CommandParser::TEST().
getOutput()
const TimedStringEvents& NetMockSimpleTimed::getOutput () inline
Get output events for golden result comparison.
Returns
All the output that was recorded on the network interface
Example:
netMockSimpleTimed net;   // No input
net.advanceTime(10);
net << "This is a test\n";
net.advanceTime(15);
net << "More test data\n";
TimedStringEvents goldenNet = {
  { 10,   "This is a test"    },
  { 15,   "More test data"    }
}
ASSERT_EQ(goldenNet, net.getOutput());
Definition at line 173 of file test_mock_net.h.
References outputEvents.
Referenced by CommandParser::TEST(), and TEST().
getString()
bool NetMockSimpleTimed::getString (WifiDebugOstream & log, std::string & returnString) inline override virtual
Get input from the net interface.
Parameters
[in] log - Debug Log (ignored)
[out] returnString - A reference to the string that's populated if there's any input
Returns
true if there's input, false otherwise.
Implements NetInterface.
Definition at line 93 of file test_mock_net.h.
References inputEvents, nextInputEvent, and time.
operator<<()
NetInterface& NetMockSimpleTimed::operator<< (char c) inline override virtual
Output a chacacter to the interface usign a streaming operator.
Parameters
[in] c The character to output
Returns
The Interface
Note: Other operators (i.e. NetInterface& operator<<(string)) are declared using templates in simple_ostream.h
Works by appending by character to the last string output event in the outputEvents vector.
Algorithm:
If c != 'n', append it to the currentOutput string.
If c == 'n', append the currentOutput to the outputEvents.
Implements NetInterface.
Definition at line 126 of file test_mock_net.h.
References currentOutput, outputEvents, and time.
operator=()
NetMockSimpleTimed& NetMockSimpleTimed::operator= (const NetMockSimpleTimed &) delete
Referenced by NetMockSimpleTimed().
setup()
void NetMockSimpleTimed::setup (DebugInterface & debugLog) inline override virtual
Implement setup required by NetInterface.
Does nothing.
Implements NetInterface.
Definition at line 82 of file test_mock_net.h.
Member Data Documentation
currentOutput
std::string NetMockSimpleTimed::currentOutput private
The current string that's being written to.
Definition at line 182 of file test_mock_net.h.
Referenced by NetMockSimpleTimed(), and operator<<().
inputEvents
const TimedStringEvents NetMockSimpleTimed::inputEvents private
Input events to be sent back to the caller.
Definition at line 186 of file test_mock_net.h.
Referenced by getString(), and NetMockSimpleTimed().
nextInputEvent
TimedStringEvents::const_iterator NetMockSimpleTimed::nextInputEvent private
The next input event that needs to be processed.
Definition at line 188 of file test_mock_net.h.
Referenced by getString(), and NetMockSimpleTimed().
outputEvents
TimedStringEvents NetMockSimpleTimed::outputEvents private
Recorded output events.
Definition at line 184 of file test_mock_net.h.
Referenced by getOutput(), and operator<<().
time
int NetMockSimpleTimed::time private
Current Time.
Definition at line 180 of file test_mock_net.h.
Referenced by advanceTime(), getString(), NetMockSimpleTimed(), and operator<<().
The documentation for this class was generated from the following file:
/home/andrew/src/beefocus/unit_tests/test_mock_net.h