BeeFocus: FS::StateStack Class Reference
FS::StateStack Class Reference
Stack of FS:States.
#include <focuser_state.h>
Classes
struct CommandPacket
Public Member Functions
StateStack ()
void reset (void)
Reset the stack to the newly initialized state.
State topState (void)
Get the top state.
StateArg topArg (void)
Get the top state's argumment.
void topArgSet (StateArg newVal)
Set the top state's argumment.
void pop (void)
Pop the top entry on the stack.
void push (State newState, StateArg newArg=StateArg())
Push a new entry onto the stack.
Private Attributes
std::vector< CommandPacket > stack
Detailed Description
Stack of FS:States.
Invariants:
In normal operation, the stack's bottom is always an ACCEPT_COMMANDS state
After construction, the stack can never be empty
If a pop operation leaves the stack empty an ERROR_STATE is pushed
Definition at line 173 of file focuser_state.h.
Constructor & Destructor Documentation
StateStack()
FS::StateStack::StateStack () inline
Definition at line 176 of file focuser_state.h.
References FS::ACCEPT_COMMANDS.
Member Function Documentation
pop()
void FS::StateStack::pop (void) inline
Pop the top entry on the stack.
Definition at line 206 of file focuser_state.h.
References FS::ERROR_STATE.
Referenced by FS::Focuser::stateDoingSteps(), FS::Focuser::stateMoving(), FS::Focuser::stateSetDir(), FS::Focuser::stateStepActiveAndWait(), FS::Focuser::stateStepInactiveAndWait(), and FS::Focuser::stateStopAtHome().
push()
void FS::StateStack::push (State newState, StateArg newArg = StateArg()) inline
Push a new entry onto the stack.
Definition at line 221 of file focuser_state.h.
Referenced by FS::Focuser::doABSPos(), FS::Focuser::doError(), FS::Focuser::doHome(), FS::Focuser::stateAcceptCommands(), FS::Focuser::stateDoingSteps(), FS::Focuser::stateMoving(), and FS::Focuser::stateStopAtHome().
reset()
void FS::StateStack::reset (void) inline
Reset the stack to the newly initialized state.
Definition at line 182 of file focuser_state.h.
Referenced by FS::Focuser::stateMoving(), FS::Focuser::stateSleep(), and FS::Focuser::stateStopAtHome().
topArg()
StateArg FS::StateStack::topArg (void) inline
Get the top state's argumment.
Definition at line 194 of file focuser_state.h.
Referenced by FS::Focuser::doSStatus(), FS::Focuser::stateDoingSteps(), FS::Focuser::stateMoving(), and FS::Focuser::stateSetDir().
topArgSet()
void FS::StateStack::topArgSet (StateArg newVal) inline
Set the top state's argumment.
Definition at line 200 of file focuser_state.h.
Referenced by FS::Focuser::stateDoingSteps().
topState()
State FS::StateStack::topState (void) inline
Get the top state.
Definition at line 188 of file focuser_state.h.
Referenced by FS::Focuser::doSStatus(), and FS::Focuser::loop().
Member Data Documentation
stack
std::vector< CommandPacket > FS::StateStack::stack private
Definition at line 234 of file focuser_state.h.
The documentation for this class was generated from the following file:
/home/andrew/src/beefocus_gh/firmware/focuser_state.h