BeeFocus: WifiInterfaceEthernet Class Reference
WifiInterfaceEthernet Class Reference
Interface to the client.
#include <net_esp8266.h>
Public Member Functions
WifiInterfaceEthernet ()
~WifiInterfaceEthernet ()
void reset (void)
void setup (DebugInterface &debugLog) override
bool getString (WifiDebugOstream &log, std::string &string) override
WifiInterfaceEthernet & operator<< (char c) override
Public Member Functions inherited from NetInterface
NetInterface ()
~NetInterface ()
Private Types
typedef std::array< WifiConnectionEthernet, 4 > ConnectionArray
Private Member Functions
void handleNewConnections (WifiDebugOstream &log)
Private Attributes
const uint16_t tcp_port {4999}
WiFiServer m_server {tcp_port}
ConnectionArray m_connections
int m_lastSlotAllocated
int m_kickout
ConnectionArray::iterator m_nextToKick
Static Private Attributes
static constexpr const char * ssid = WifiSecrets::ssid
static constexpr const char * password = WifiSecrets::password
Detailed Description
Interface to the client.
This class's one job is to provide an interface to the client.
Definition at line 72 of file net_esp8266.h.
Member Typedef Documentation
ConnectionArray
typedef std::array< WifiConnectionEthernet, 4 > WifiInterfaceEthernet::ConnectionArray private
Definition at line 100 of file net_esp8266.h.
Constructor & Destructor Documentation
WifiInterfaceEthernet()
WifiInterfaceEthernet::WifiInterfaceEthernet () inline
Definition at line 75 of file net_esp8266.h.
References WifiConnectionEthernet::reset().
~WifiInterfaceEthernet()
WifiInterfaceEthernet::~WifiInterfaceEthernet () inline
Definition at line 79 of file net_esp8266.h.
References WifiConnectionEthernet::getString(), WifiConnectionEthernet::operator<<(), WifiConnectionEthernet::reset(), and setup().
Member Function Documentation
getString()
bool WifiInterfaceEthernet::getString (WifiDebugOstream & log, std::string & string) override virtual
Implements NetInterface.
Definition at line 36 of file net_esp8266.cpp.
References handleNewConnections(), and m_connections.
handleNewConnections()
void WifiInterfaceEthernet::handleNewConnections (WifiDebugOstream & log) private
Definition at line 45 of file net_esp8266.cpp.
References m_connections, m_nextToKick, and m_server.
Referenced by getString().
operator<<()
WifiInterfaceEthernet & WifiInterfaceEthernet::operator<< (char c) override virtual
Implements NetInterface.
Definition at line 75 of file net_esp8266.cpp.
References m_connections.
reset()
void WifiInterfaceEthernet::reset (void)
Definition at line 84 of file net_esp8266.cpp.
References m_connections.
setup()
void WifiInterfaceEthernet::setup (DebugInterface & debugLog) override virtual
Implements NetInterface.
Definition at line 6 of file net_esp8266.cpp.
References m_server, password, ssid, and tcp_port.
Member Data Documentation
m_connections
ConnectionArray WifiInterfaceEthernet::m_connections private
Definition at line 101 of file net_esp8266.h.
Referenced by getString(), handleNewConnections(), operator<<(), and reset().
m_kickout
int WifiInterfaceEthernet::m_kickout private
Definition at line 103 of file net_esp8266.h.
m_lastSlotAllocated
int WifiInterfaceEthernet::m_lastSlotAllocated private
Definition at line 102 of file net_esp8266.h.
m_nextToKick
ConnectionArray::iterator WifiInterfaceEthernet::m_nextToKick private
Definition at line 104 of file net_esp8266.h.
Referenced by handleNewConnections().
m_server
WiFiServer WifiInterfaceEthernet::m_server {tcp_port} private
Definition at line 99 of file net_esp8266.h.
Referenced by handleNewConnections(), and setup().
password
constexpr const char* WifiInterfaceEthernet::password = WifiSecrets::password static private
Definition at line 96 of file net_esp8266.h.
Referenced by setup().
ssid
constexpr const char* WifiInterfaceEthernet::ssid = WifiSecrets::ssid static private
Definition at line 95 of file net_esp8266.h.
Referenced by setup().
tcp_port
const uint16_t WifiInterfaceEthernet::tcp_port {4999} private
Definition at line 97 of file net_esp8266.h.
Referenced by setup().
The documentation for this class was generated from the following files:
/home/andrew/src/beefocus/firmware/net_esp8266.h
/home/andrew/src/beefocus/firmware/net_esp8266.cpp