BeeFocus: FS::Focuser Class Reference
FS::Focuser Class Reference
#include <focuser_state.h>
Public Types
using ptrToMember = unsigned int(Focuser::*)(void)
Public Member Functions
Focuser (std::unique_ptr< NetInterface > netArg, std::unique_ptr< HWI > hardwareArg, std::unique_ptr< DebugInterface > debugArg)
Focuser State Constructor.
unsigned int loop ()
Update the Focuser's State.
void setTimingParams (const TimingParams &tp)
Set the maximum number of steps we'll do at a time.
Static Public Attributes
static const std::unordered_map< CommandParser::Command, void(Focuser::*)(CommandParser::CommandPacket), EnumHash > commandImpl
static const std::unordered_map< State, ptrToMember, EnumHash > stateImpl
Private Types
enum MotorState { MotorState::ON, MotorState::OFF }
Private Member Functions
Focuser (const Focuser &other)=delete
Deleted copy constructor.
Focuser ()=delete
Deleted default constructor.
Focuser & operator= (const Focuser &)=delete
Deleted assignment operator.
void processCommand (CommandParser::CommandPacket cp)
unsigned int stateAcceptCommands (void)
Wait for commands from the network interface.
unsigned int stateMoving (void)
Move to position.
unsigned int stateDoingSteps (void)
Move the stepper.
unsigned int stateSetDir (void)
If needed, Change the state of the direction pin and pause.
unsigned int stateStepActiveAndWait (void)
Set the Stepper to active (i.e., start step) and wait.
unsigned int stateStepInactiveAndWait (void)
Set the Stepper to inactive (i.e., finish step) and wait.
unsigned int stateStopAtHome (void)
Rewind the focuser until the home input is active.
unsigned int stateSleep (void)
Low power mode.
unsigned int stateError (void)
If we land in this state, complain a lot.
void doAbort (CommandParser::CommandPacket)
void doHome (CommandParser::CommandPacket)
void doPStatus (CommandParser::CommandPacket)
void doSStatus (CommandParser::CommandPacket)
void doHStatus (CommandParser::CommandPacket)
void doABSPos (CommandParser::CommandPacket)
void doError (CommandParser::CommandPacket)
void setMotor (WifiDebugOstream &log, MotorState)
Private Attributes
StateStack stateStack
std::unique_ptr< NetInterface > net
std::unique_ptr< HWI > hardware
std::unique_ptr< DebugInterface > debugLog
TimingParams timingParams
Dir dir
What direction are we going?
MotorState motorState
Is the Stepper Motor On or Off.
int focuserPosition
What is the focuser's position of record.
bool isHomed
Is the focuser homed?
unsigned int time
Focuser uptime in MS.
unsigned int uSecRemainder
For computing time in Focuser::loop.
unsigned int timeLastInterruptingCommandOccured
Time the last command that could have caused an interrupt happened.
Detailed Description
Definition at line 237 of file focuser_state.h.
Member Typedef Documentation
ptrToMember
using FS::Focuser::ptrToMember = unsigned int (Focuser::*) (void)
Definition at line 284 of file focuser_state.h.
Member Enumeration Documentation
MotorState
enum FS::Focuser::MotorState strong private
Enumerator
ON
OFF
Definition at line 340 of file focuser_state.h.
Constructor & Destructor Documentation
Focuser() [1/3]
Focuser::Focuser (std::unique_ptr< NetInterface > netArg, std::unique_ptr< HWI > hardwareArg, std::unique_ptr< DebugInterface > debugArg)
Focuser State Constructor.
Parameters
[in] netArg - Interface to the network
[in] hardwareArg - Interface to the Hardware
[in] debugArg - Interface to the debug logger.
Definition at line 63 of file focuser_state.cpp.
References debugLog, HWI::DIR, dir, HWI::DIR_FORWARD, focuserPosition, FS::FORWARD, hardware, HWI::HOME, isHomed, HWI::M_INPUT, HWI::M_OUTPUT, HWI::MOTOR_ENA, net, ON, setMotor(), HWI::STEP, HWI::STEP_INACTIVE, time, timeLastInterruptingCommandOccured, and uSecRemainder.
Focuser() [2/3]
FS::Focuser::Focuser (const Focuser & other) private delete
Deleted copy constructor.
Focuser() [3/3]
FS::Focuser::Focuser () private delete
Deleted default constructor.
Member Function Documentation
doAbort()
void Focuser::doAbort (CommandParser::CommandPacket cp) private
Definition at line 107 of file focuser_state.cpp.
doABSPos()
void Focuser::doABSPos (CommandParser::CommandPacket cp) private
Definition at line 149 of file focuser_state.cpp.
References focuserPosition, FS::MOVING, CommandParser::CommandPacket::optionalArg, FS::StateStack::push(), and stateStack.
doError()
void Focuser::doError (CommandParser::CommandPacket cp) private
Definition at line 162 of file focuser_state.cpp.
References FS::ERROR_STATE, FS::StateStack::push(), and stateStack.
doHome()
void Focuser::doHome (CommandParser::CommandPacket cp) private
Definition at line 113 of file focuser_state.cpp.
References FS::StateStack::push(), stateStack, and FS::STOP_AT_HOME.
doHStatus()
void Focuser::doHStatus (CommandParser::CommandPacket cp) private
Definition at line 139 of file focuser_state.cpp.
References debugLog, isHomed, and net.
doPStatus()
void Focuser::doPStatus (CommandParser::CommandPacket cp) private
Definition at line 120 of file focuser_state.cpp.
References debugLog, focuserPosition, and net.
doSStatus()
void Focuser::doSStatus (CommandParser::CommandPacket cp) private
Definition at line 128 of file focuser_state.cpp.
References debugLog, net, FS::stateNames, stateStack, FS::StateStack::topArg(), and FS::StateStack::topState().
loop()
unsigned int Focuser::loop (void)
Update the Focuser's State.
Returns
The amount of time the caller should wait (in microsecodns) before calling loop again.
Definition at line 383 of file focuser_state.cpp.
References stateImpl, stateStack, time, FS::StateStack::topState(), and uSecRemainder.
Referenced by simulateFocuser().
operator=()
Focuser& FS::Focuser::operator= (const Focuser &) private delete
Deleted assignment operator.
processCommand()
void Focuser::processCommand (CommandParser::CommandPacket cp) private
Definition at line 168 of file focuser_state.cpp.
References CommandParser::CommandPacket::command, commandImpl, FS::doesCommandInterrupt, time, and timeLastInterruptingCommandOccured.
Referenced by stateAcceptCommands(), stateMoving(), stateSleep(), and stateStopAtHome().
setMotor()
void Focuser::setMotor (WifiDebugOstream & log, MotorState m) private
Definition at line 393 of file focuser_state.cpp.
References hardware, HWI::MOTOR_ENA, HWI::MOTOR_OFF, HWI::MOTOR_ON, motorState, and ON.
Referenced by Focuser(), and stateSleep().
setTimingParams()
void FS::Focuser::setTimingParams (const TimingParams & tp) inline
Set the maximum number of steps we'll do at a time.
Parameters
[in] maxSteps - The maximum number of steps the focuser should move before we check the network interface for a new command.
On the ESP8266 checking the network to see if there's anything new is a realitively expensive operation - checking often hurts performance.
In unit testing, we want to decrease this number so we'll check for interrupts move frequently.
Definition at line 275 of file focuser_state.h.
stateAcceptCommands()
unsigned int Focuser::stateAcceptCommands (void) private
Wait for commands from the network interface.
Definition at line 178 of file focuser_state.cpp.
References CommandParser::checkForCommands(), debugLog, FS::TimingParams::getEpochBetweenCommandChecks(), FS::TimingParams::getInactivityToSleep(), net, CommandParser::NoCommand, processCommand(), FS::StateStack::push(), FS::SLEEP, stateStack, time, timeLastInterruptingCommandOccured, and timingParams.
stateDoingSteps()
unsigned int Focuser::stateDoingSteps (void) private
Move the stepper.
steps
Definition at line 238 of file focuser_state.cpp.
References dir, focuserPosition, FS::FORWARD, FS::StateArg::getInt(), FS::StateStack::pop(), FS::StateStack::push(), stateStack, FS::STEPPER_ACTIVE_AND_WAIT, FS::STEPPER_INACTIVE_AND_WAIT, FS::StateStack::topArg(), and FS::StateStack::topArgSet().
stateError()
unsigned int Focuser::stateError (void) private
If we land in this state, complain a lot.
Definition at line 376 of file focuser_state.cpp.
References debugLog, and net.
stateMoving()
unsigned int Focuser::stateMoving (void) private
Move to position.
Definition at line 257 of file focuser_state.cpp.
References CommandParser::checkForCommands(), debugLog, FS::DO_STEPS, FS::doesCommandInterrupt, focuserPosition, FS::FORWARD, FS::StateArg::getInt(), FS::TimingParams::getMaxStepsBetweenChecks(), net, CommandParser::NoCommand, FS::StateStack::pop(), processCommand(), FS::StateStack::push(), FS::StateStack::reset(), FS::REVERSE, FS::SET_DIR, stateStack, timingParams, and FS::StateStack::topArg().
stateSetDir()
unsigned int Focuser::stateSetDir (void) private
If needed, Change the state of the direction pin and pause.
Definition at line 203 of file focuser_state.cpp.
References HWI::DIR, dir, HWI::DIR_BACKWARD, HWI::DIR_FORWARD, FS::FORWARD, FS::StateArg::getDir(), hardware, FS::StateStack::pop(), FS::REVERSE, stateStack, and FS::StateStack::topArg().
stateSleep()
unsigned int Focuser::stateSleep (void) private
Low power mode.
Definition at line 341 of file focuser_state.cpp.
References CommandParser::checkForCommands(), debugLog, FS::doesCommandInterrupt, FS::TimingParams::getEpochForSleepCommandChecks(), FS::TimingParams::getTimeToPowerStepper(), motorState, net, CommandParser::NoCommand, OFF, ON, processCommand(), FS::StateStack::reset(), setMotor(), stateStack, time, and timingParams.
stateStepActiveAndWait()
unsigned int Focuser::stateStepActiveAndWait (void) private
Set the Stepper to active (i.e., start step) and wait.
Definition at line 231 of file focuser_state.cpp.
References hardware, FS::StateStack::pop(), stateStack, HWI::STEP, and HWI::STEP_ACTIVE.
stateStepInactiveAndWait()
unsigned int Focuser::stateStepInactiveAndWait (void) private
Set the Stepper to inactive (i.e., finish step) and wait.
Definition at line 224 of file focuser_state.cpp.
References hardware, FS::StateStack::pop(), stateStack, HWI::STEP, and HWI::STEP_INACTIVE.
stateStopAtHome()
unsigned int Focuser::stateStopAtHome (void) private
Rewind the focuser until the home input is active.
Definition at line 296 of file focuser_state.cpp.
References CommandParser::checkForCommands(), debugLog, FS::DO_STEPS, FS::doesCommandInterrupt, focuserPosition, FS::TimingParams::getMaxStepsBetweenChecks(), hardware, HWI::HOME, HWI::HOME_ACTIVE, isHomed, motorState, net, CommandParser::NoCommand, ON, FS::StateStack::pop(), processCommand(), FS::StateStack::push(), FS::StateStack::reset(), FS::REVERSE, FS::SET_DIR, stateStack, and timingParams.
Member Data Documentation
commandImpl
const std::unordered_map< CommandParser::Command, void(Focuser::*)(CommandParser::CommandPacket), EnumHash > Focuser::commandImpl static
Initial value:
=
{
  { CommandParser::Command::Abort,      &Focuser::doAbort },
  { CommandParser::Command::Home,       &Focuser::doHome },
  { CommandParser::Command::PStatus,    &Focuser::doPStatus },
  { CommandParser::Command::SStatus,    &Focuser::doSStatus },
  { CommandParser::Command::HStatus,    &Focuser::doHStatus },
  { CommandParser::Command::ABSPos,     &Focuser::doABSPos },
  { CommandParser::Command::NoCommand,  &Focuser::doError },
}
Definition at line 282 of file focuser_state.h.
Referenced by processCommand(), and TEST().
debugLog
std::unique_ptr<DebugInterface> FS::Focuser::debugLog private
Definition at line 329 of file focuser_state.h.
Referenced by doHStatus(), doPStatus(), doSStatus(), Focuser(), stateAcceptCommands(), stateError(), stateMoving(), stateSleep(), and stateStopAtHome().
dir
Dir FS::Focuser::dir private
What direction are we going?
FORWARD = counting up. REVERSE = counting down.
Definition at line 338 of file focuser_state.h.
Referenced by Focuser(), stateDoingSteps(), and stateSetDir().
focuserPosition
int FS::Focuser::focuserPosition private
What is the focuser's position of record.
Definition at line 351 of file focuser_state.h.
Referenced by doABSPos(), doPStatus(), Focuser(), stateDoingSteps(), stateMoving(), and stateStopAtHome().
hardware
std::unique_ptr<HWI> FS::Focuser::hardware private
Definition at line 328 of file focuser_state.h.
Referenced by Focuser(), setMotor(), stateSetDir(), stateStepActiveAndWait(), stateStepInactiveAndWait(), and stateStopAtHome().
isHomed
bool FS::Focuser::isHomed private
Is the focuser homed?
Definition at line 354 of file focuser_state.h.
Referenced by doHStatus(), Focuser(), and stateStopAtHome().
motorState
MotorState FS::Focuser::motorState private
Is the Stepper Motor On or Off.
Definition at line 346 of file focuser_state.h.
Referenced by setMotor(), stateSleep(), and stateStopAtHome().
net
std::unique_ptr<NetInterface> FS::Focuser::net private
Definition at line 327 of file focuser_state.h.
Referenced by doHStatus(), doPStatus(), doSStatus(), Focuser(), stateAcceptCommands(), stateError(), stateMoving(), stateSleep(), and stateStopAtHome().
stateImpl
const std::unordered_map< State, unsigned int(Focuser::*)(void), EnumHash > Focuser::stateImpl static
Initial value:
=
{
  { State::ACCEPT_COMMANDS,           &Focuser::stateAcceptCommands },
  { State::DO_STEPS,                  &Focuser::stateDoingSteps },
  { State::STEPPER_INACTIVE_AND_WAIT, &Focuser::stateStepInactiveAndWait },
  { State::STEPPER_ACTIVE_AND_WAIT,   &Focuser::stateStepActiveAndWait },
  { State::SET_DIR,                   &Focuser::stateSetDir },
  { State::MOVING,                    &Focuser::stateMoving },
  { State::STOP_AT_HOME,              &Focuser::stateStopAtHome },
  { State::SLEEP,                     &Focuser::stateSleep },
  { State::ERROR_STATE,               &Focuser::stateError }
}
Definition at line 285 of file focuser_state.h.
Referenced by loop(), and TEST().
stateStack
StateStack FS::Focuser::stateStack private
Definition at line 296 of file focuser_state.h.
Referenced by doABSPos(), doError(), doHome(), doSStatus(), loop(), stateAcceptCommands(), stateDoingSteps(), stateMoving(), stateSetDir(), stateSleep(), stateStepActiveAndWait(), stateStepInactiveAndWait(), and stateStopAtHome().
time
unsigned int FS::Focuser::time private
Focuser uptime in MS.
Definition at line 357 of file focuser_state.h.
Referenced by Focuser(), loop(), processCommand(), stateAcceptCommands(), and stateSleep().
timeLastInterruptingCommandOccured
unsigned int FS::Focuser::timeLastInterruptingCommandOccured private
Time the last command that could have caused an interrupt happened.
Definition at line 363 of file focuser_state.h.
Referenced by Focuser(), processCommand(), and stateAcceptCommands().
timingParams
TimingParams FS::Focuser::timingParams private
Definition at line 331 of file focuser_state.h.
Referenced by stateAcceptCommands(), stateMoving(), stateSleep(), and stateStopAtHome().
uSecRemainder
unsigned int FS::Focuser::uSecRemainder private
For computing time in Focuser::loop.
Definition at line 360 of file focuser_state.h.
Referenced by Focuser(), and loop().
The documentation for this class was generated from the following files:
/home/andrew/src/beefocus_gh/firmware/focuser_state.h
/home/andrew/src/beefocus_gh/firmware/focuser_state.cpp