BeeFocus: HWMockTimed Class Reference
HWMockTimed Class Reference
Testing Mock for hardware events.
#include <test_mock_hardware.h>
Public Member Functions
HWMockTimed (const HWTimedEvents &hwIn)
Class Constructor.
HWMockTimed ()=delete
HWMockTimed (const HWMockTimed &)=delete
HWMockTimed & operator= (const HWMockTimed &)=delete
void DigitalWrite (Pin pin, PinState state) override
Mock DigitalWrite hardware interface.
void PinMode (Pin pin, PinIOMode mode) override
Mock PinMode hardware interface.
PinState DigitalRead (Pin pin) override
Mock DigitalRead hardware interface.
void advanceTime (int ticks)
Advance simulated time.
const HWTimedEvents & getOutEvents () const
Get output events for golden result comparison.
Public Member Functions inherited from HWI
virtual void DigitalWrite (Pin pin, PinState state)=0
virtual void PinMode (Pin pin, PinIOMode mode)=0
virtual PinState DigitalRead (Pin pin)=0
Private Attributes
int time
Current tIme.
HWTimedEvents outEvents
Recorded output events.
const HWTimedEvents inEvents
Input events to be sent back to the caller.
HWTimedEvents::const_iterator nextInputEvent
Next input event that needs to be processed.
std::unordered_map< Pin, PinState, EnumHash > inputStates
The current state of each input pin.
Additional Inherited Members
Public Types inherited from HWI
enum Pin {
Pin::START_OF_PINS = 0, Pin::STEP = 0, Pin::DIR, Pin::MOTOR_ENA,
Pin::HOME, Pin::END_OF_PINS
}
enum PinState {
PinState::START_OF_PIN_STATES = 0, PinState::STEP_ACTIVE = 0, PinState::STEP_INACTIVE, PinState::DIR_FORWARD,
PinState::DIR_BACKWARD, PinState::MOTOR_ON, PinState::MOTOR_OFF, PinState::HOME_ACTIVE,
PinState::HOME_INACTIVE, PinState::END_OF_PIN_STATES
}
enum PinIOMode { PinIOMode::START_OF_PIN_IO_MODES = 0, PinIOMode::M_OUTPUT = 0, PinIOMode::M_INPUT = 1, PinIOMode::END_OF_IO_MODES }
Static Public Attributes inherited from HWI
static const std::unordered_map< Pin, std::string, EnumHash > pinNames
static const std::unordered_map< PinState, std::string, EnumHash > pinStateNames
static const std::unordered_map< PinIOMode, std::string, EnumHash > pinIOModeNames
Detailed Description
Testing Mock for hardware events.
Testing Mock for hardware events
HWMockTimed implements a mock Hardware Interface (HWI) that's used in unit testing. The class implements testing mocks for the interfaces required by the HWI class. In addition to that, the class does the following:
Maintain Time. The class simulates the passage of time. advanceTime is called to "move" time forward
Record Output. Whenever an output pin is changed on the hardware mock the event and event time are recorded. Tests can use this to verify that the output matches a golden result.
Simulate Input. On class construction, the caller can specify a series of input events and the time those events occur at. i.e., the caller can see "at time 20ms the HOME input will change state to active"
Definition at line 31 of file test_mock_hardware.h.
Constructor & Destructor Documentation
HWMockTimed() [1/3]
HWMockTimed::HWMockTimed (const HWTimedEvents & hwIn) inline
Class Constructor.
Parameters
[in] HWTimedEvents - Simulated Input Events. A vector of input events and they time they take place at. See HWTimedEvents for examples.
Definition at line 41 of file test_mock_hardware.h.
References advanceTime(), HWMockTimed(), inEvents, nextInputEvent, and operator=().
HWMockTimed() [2/3]
HWMockTimed::HWMockTimed () delete
Referenced by HWMockTimed().
HWMockTimed() [3/3]
HWMockTimed::HWMockTimed (const HWMockTimed &) delete
Member Function Documentation
advanceTime()
void HWMockTimed::advanceTime (int ticks) inline
Advance simulated time.
param[in] ticks - Time to advance in ms
Does the following:
Advance the official time of the hardware mock by tick ms.
Process all input events up to the new time.
Definition at line 122 of file test_mock_hardware.h.
References inEvents, inputStates, nextInputEvent, and time.
Referenced by HWMockTimed(), and simulateFocuser().
DigitalRead()
PinState HWMockTimed::DigitalRead (Pin pin) inline override
Mock DigitalRead hardware interface.
Parameters
[in] pin - The pin being read from
Returns
- The pin's current state
Returns the current state of the pin. Any pin used by this interface has to have it's state defined at class construction time. i.e.
HWTimedEvents hwInput= {
  { 0,   { HWI::Pin::HOME,        HWI::PinState::HOME_INACTIVE} },
  { 10,  { HWI::Pin::HOME,        HWI::PinState::HOME_INACTIVE} },
};
HWMockTimed hw(hwInput) :
hw.DigitalRead(HWI::Pin::HOME)  // Will return HOME_INACTIVE
hw.advanceTime(5)               // Time = 5
hw.DigitalRead(HWI::Pin::HOME)  // Will still return HOME_INACTIVE
hw.advanceTime(5)               // Time = 10
hw.DigitalRead(HWI::Pin::HOME)  // Will now return HOME_ACTIVE
Definition at line 106 of file test_mock_hardware.h.
References inputStates.
DigitalWrite()
void HWMockTimed::DigitalWrite (Pin pin, PinState state) inline override
Mock DigitalWrite hardware interface.
Parameters
[in] pin - The pin being written to
[in] pinState - The pin's new state
Records the event and time for golden result comparison.
Definition at line 64 of file test_mock_hardware.h.
References outEvents, and time.
getOutEvents()
const HWTimedEvents& HWMockTimed::getOutEvents () const inline
Get output events for golden result comparison.
Returns
All output events that were recorded on the hardware
Example:
HWTimedEvents hwInput;  // No input
HWMockTimed hw(hwInput) :
// Set Stepper Pin to Output
hw.PinMode(HWI::Pin::STEP,   HWI::PinIOMode::M_OUTPUT);
hw.PinMode(HWI::Pin::STEP,   HWI::PinState::STEP_INACTIVE);
// Do a step
hw.advanceTime(10)
hw.PinMode(HWI::Pin::STEP,   HWI::PinState::STEP_ACTIVE);
hw.advanceTime(1)
hw.PinMode(HWI::Pin::STEP,   HWI::PinState::STEP_INACTIVE);
// Golden Results
HWTimedEvents goldenHW = {
  { 0,  {HWI::Pin::Step,   HWI::PinIOMode::M_OUTPUT      } },
  { 0,  {HWI::Pin::Step,   HWI::PinState::STEP_INACTIVE  } },
  { 10, {HWI::Pin::Step,   HWI::PinState::STEP_ACTIVE } },
  { 11, {HWI::Pin::Step,   HWI::PinState::STEP_ACTIVE } }
}
// Compare
ASSERT_EQ(goldenHw, hw.getOutEvents());
Definition at line 168 of file test_mock_hardware.h.
References outEvents.
operator=()
HWMockTimed& HWMockTimed::operator= (const HWMockTimed &) delete
Referenced by HWMockTimed().
PinMode()
void HWMockTimed::PinMode (Pin pin, PinIOMode mode) inline override
Mock PinMode hardware interface.
Parameters
[in] pin - The pin being written to
[in] mode - The pin's new mode (i.e., output or input)
Records the event and time for golden result comparison.
Definition at line 77 of file test_mock_hardware.h.
References outEvents, and time.
Member Data Documentation
inEvents
const HWTimedEvents HWMockTimed::inEvents private
Input events to be sent back to the caller.
Definition at line 179 of file test_mock_hardware.h.
Referenced by advanceTime(), and HWMockTimed().
inputStates
std::unordered_map<Pin,PinState,EnumHash> HWMockTimed::inputStates private
The current state of each input pin.
Definition at line 183 of file test_mock_hardware.h.
Referenced by advanceTime(), and DigitalRead().
nextInputEvent
HWTimedEvents::const_iterator HWMockTimed::nextInputEvent private
Next input event that needs to be processed.
Definition at line 181 of file test_mock_hardware.h.
Referenced by advanceTime(), and HWMockTimed().
outEvents
HWTimedEvents HWMockTimed::outEvents private
Recorded output events.
Definition at line 177 of file test_mock_hardware.h.
Referenced by DigitalWrite(), getOutEvents(), and PinMode().
time
int HWMockTimed::time private
Current tIme.
Definition at line 175 of file test_mock_hardware.h.
Referenced by advanceTime(), DigitalWrite(), and PinMode().
The documentation for this class was generated from the following file:
/home/andrew/src/beefocus_gh/unit_tests/test_mock_hardware.h