BeeFocus: /home/andrew/src/beefocus_gh/unit_tests/test_focuser_state.cpp File Reference
test_focuser_state.cpp File Reference
#include <gtest/gtest.h>
#include "focuser_state.h"
#include "test_mock_debug.h"
#include "test_mock_event.h"
#include "test_mock_hardware.h"
#include "test_mock_net.h"
Functions
std::unique_ptr< FS::Focuser > make_focuser (const TimedStringEvents &wifiIn, const HWTimedEvents &hwIn, NetMockSimpleTimed *&net_interface, HWMockTimed *&hw_interface)
void simulateFocuser (FS::Focuser *focuser, NetMockSimpleTimed *wifiAlias, HWMockTimed *hwMockAlias, unsigned int endTime)
Simulate the focuser.
TEST (FOCUSER_STATE, allCommandsHaveInterruptStatus)
TEST (FOCUSER_STATE, allCommandsHaveImplementations)
TEST (FOCUSER_STATE, allStatesHaveImplementations)
TEST (FOCUSER_STATE, allStatesHaveDebugNames)
TEST (FOCUSER_STATE, init_Focuser)
Init the focuser.
TEST (FOCUSER_STATE, run_status)
Init the focuser and pass in some status commands.
TEST (FOCUSER_STATE, run_abs_pos)
TEST (FOCUSER_STATE, run_abs_pos_double_forward)
Test double abs_pos command.
TEST (FOCUSER_STATE, run_abs_pos_with_backlash_correction)
Test double abs_pos command with backlash correct.
TEST (FOCUSER_STATE, home_focuser)
TEST (FOCUSER_STATE, sstatus_while_moving)
TEST (FOCUSER_STATE, abort_while_moving)
TEST (FOCUSER_STATE, abort_while_homing)
TEST (FOCUSER_STATE, new_move_while_moving)
TEST (FOCUSER_STATE, new_move_while_homing)
TEST (FOCUSER_STATE, new_home_while_moving)
TEST (FOCUSER_STATE, new_home_while_homing)
TEST (FOCUSER_STATE, interrupt_during_backlash_correction)
TEST (FOCUSER_STATE, enterSleepModeAndWake)
Variables
HWTimedEvents goldenHWStart
Function Documentation
make_focuser()
std::unique_ptr<FS::Focuser> make_focuser (const TimedStringEvents & wifiIn, const HWTimedEvents & hwIn, NetMockSimpleTimed *& net_interface, HWMockTimed *& hw_interface)
Definition at line 20 of file test_focuser_state.cpp.
References focuser.
Referenced by TEST().
simulateFocuser()
void simulateFocuser (FS::Focuser * focuser, NetMockSimpleTimed * wifiAlias, HWMockTimed * hwMockAlias, unsigned int endTime)
Simulate the focuser.
Parameters
[out] Focuser - A pointer to the focuser.
[in] wifiAlisa - A pointer to the WIFI/ Network Mock
[in] end_time - How long (in MS) to run the focuser for.
Definition at line 62 of file test_focuser_state.cpp.
References HWMockTimed::advanceTime(), NetMockSimpleTimed::advanceTime(), and FS::Focuser::loop().
Referenced by TEST().
TEST() [1/19]
TEST (FOCUSER_STATE , allCommandsHaveInterruptStatus)
Definition at line 81 of file test_focuser_state.cpp.
References FS::doesCommandInterrupt, CommandParser::EndOfCommands, and CommandParser::StartOfCommands.
TEST() [2/19]
TEST (FOCUSER_STATE , allCommandsHaveImplementations)
Definition at line 91 of file test_focuser_state.cpp.
References FS::Focuser::commandImpl, CommandParser::EndOfCommands, and CommandParser::StartOfCommands.
TEST() [3/19]
TEST (FOCUSER_STATE , allStatesHaveImplementations)
Definition at line 103 of file test_focuser_state.cpp.
References FS::END_OF_STATES, FS::START_OF_STATES, and FS::Focuser::stateImpl.
TEST() [4/19]
TEST (FOCUSER_STATE , allStatesHaveDebugNames)
Definition at line 115 of file test_focuser_state.cpp.
References FS::END_OF_STATES, FS::START_OF_STATES, and FS::stateNames.
TEST() [5/19]
TEST (FOCUSER_STATE , init_Focuser)
Init the focuser.
Definition at line 129 of file test_focuser_state.cpp.
References focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_INACTIVE, make_focuser(), and simulateFocuser().
TEST() [6/19]
TEST (FOCUSER_STATE , run_status)
Init the focuser and pass in some status commands.
Definition at line 154 of file test_focuser_state.cpp.
References focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), and testFilterComments().
TEST() [7/19]
TEST (FOCUSER_STATE , run_abs_pos)
Definition at line 182 of file test_focuser_state.cpp.
References focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [8/19]
TEST (FOCUSER_STATE , run_abs_pos_double_forward)
Test double abs_pos command.
Focuser should advance to 3, then advance to 5 on the next 'accept commands' tick after 50ms
TODO - modify accept for commands so it tries to sync up with 10ms epochs to make unit testing easier.
Definition at line 222 of file test_focuser_state.cpp.
References focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [9/19]
TEST (FOCUSER_STATE , run_abs_pos_with_backlash_correction)
Test double abs_pos command with backlash correct.
Focuser should advance to 3, then rewind to 2 on the next 'accept commands' tick after 50ms. The rewind will got 0 0 to try to clear backlash and then forward to 2.
Definition at line 265 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, HWI::DIR_FORWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [10/19]
TEST (FOCUSER_STATE , home_focuser)
Definition at line 309 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, HWI::DIR_FORWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_ACTIVE, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [11/19]
TEST (FOCUSER_STATE , sstatus_while_moving)
Definition at line 358 of file test_focuser_state.cpp.
References focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [12/19]
TEST (FOCUSER_STATE , abort_while_moving)
Definition at line 402 of file test_focuser_state.cpp.
References focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [13/19]
TEST (FOCUSER_STATE , abort_while_homing)
Definition at line 439 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_ACTIVE, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [14/19]
TEST (FOCUSER_STATE , new_move_while_moving)
Definition at line 484 of file test_focuser_state.cpp.
References focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [15/19]
TEST (FOCUSER_STATE , new_move_while_homing)
Definition at line 521 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, HWI::DIR_FORWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_ACTIVE, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [16/19]
TEST (FOCUSER_STATE , new_home_while_moving)
Definition at line 579 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_ACTIVE, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [17/19]
TEST (FOCUSER_STATE , new_home_while_homing)
Definition at line 630 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_ACTIVE, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [18/19]
TEST (FOCUSER_STATE , interrupt_during_backlash_correction)
Definition at line 681 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_INACTIVE, make_focuser(), simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
TEST() [19/19]
TEST (FOCUSER_STATE , enterSleepModeAndWake)
Definition at line 723 of file test_focuser_state.cpp.
References HWI::DIR, HWI::DIR_BACKWARD, focuser, NetMockSimpleTimed::getOutput(), goldenHWStart, HWI::HOME, HWI::HOME_ACTIVE, HWI::HOME_INACTIVE, make_focuser(), HWI::MOTOR_ENA, HWI::MOTOR_OFF, HWI::MOTOR_ON, simulateFocuser(), HWI::STEP, HWI::STEP_ACTIVE, HWI::STEP_INACTIVE, and testFilterComments().
Variable Documentation
goldenHWStart
HWTimedEvents goldenHWStart
Initial value:
= {
  {  0, { HWI::Pin::STEP,       HWI::PinIOMode::M_OUTPUT     } },
  {  0, { HWI::Pin::DIR,        HWI::PinIOMode::M_OUTPUT     } },
  {  0, { HWI::Pin::MOTOR_ENA,  HWI::PinIOMode::M_OUTPUT     } },
  {  0, { HWI::Pin::HOME,       HWI::PinIOMode::M_INPUT      } },
  {  0, { HWI::Pin::MOTOR_ENA,  HWI::PinState::MOTOR_ON      } },
  {  0, { HWI::Pin::DIR,        HWI::PinState::DIR_FORWARD   } },
  {  0, { HWI::Pin::STEP,       HWI::PinState::STEP_INACTIVE } },
}
Definition at line 9 of file test_focuser_state.cpp.
Referenced by TEST().