BeeFocus: /home/andrew/src/beefocus_gh/unit_tests/test_mock_event.h File Reference
test_mock_event.h File Reference
#include <iostream>
#include <gtest/gtest.h>
#include "hardware_interface.h"
Classes
class HWEvent
a Hardware Event
class TimedEvent< Event >
A Timed Event of some kind for unit testing.
Typedefs
using TimedStringEvent = TimedEvent< std::string >
A timed string event (i.e., network input or output)
using TimedStringEvents = std::vector< TimedStringEvent >
A vector of timed string events.
using HWTimedEvent = TimedEvent< HWEvent >
A timed hardware event (i.e., a state change on a pin)
using HWTimedEvents = std::vector< HWTimedEvent >
A vector of timed hardware events.
Functions
std::ostream & operator<< (std::ostream &stream, const HWEvent &event)
Output stream operator for Hardware Events.
template<class Event >
std::ostream & operator<< (std::ostream &stream, const TimedEvent< Event > &timedEvent)
std::ostream << operator for a timed event
Typedef Documentation
HWTimedEvent
using HWTimedEvent = TimedEvent<HWEvent>
A timed hardware event (i.e., a state change on a pin)
Definition at line 208 of file test_mock_event.h.
HWTimedEvents
using HWTimedEvents = std::vector<HWTimedEvent>
A vector of timed hardware events.
Definition at line 213 of file test_mock_event.h.
TimedStringEvent
using TimedStringEvent = TimedEvent<std::string>
A timed string event (i.e., network input or output)
Definition at line 198 of file test_mock_event.h.
TimedStringEvents
using TimedStringEvents = std::vector<TimedStringEvent>
A vector of timed string events.
Definition at line 203 of file test_mock_event.h.
Function Documentation
operator<<() [1/2]
std::ostream& operator<< (std::ostream & stream, const HWEvent & event) inline
Output stream operator for Hardware Events.
Used by gtest to output useful information when a test fails.
Parameters
[out] stream The stream to outputting to
[in] event The hardware event being outputting.
Definition at line 125 of file test_mock_event.h.
References HWEvent::getIO(), HWEvent::getMode(), HWEvent::getPin(), HWEvent::isIO(), HWI::pinIOModeNames, HWI::pinNames, and HWI::pinStateNames.
operator<<() [2/2]
template<class Event > std::ostream& operator<< (std::ostream & stream, const TimedEvent< Event > & timedEvent)
std::ostream << operator for a timed event
Used by gtest to output useful information when a test fails.
Parameters
[out] stream The stream to outputting to
[in] event The hardware event being outputting.
Definition at line 187 of file test_mock_event.h.
References TimedEvent< Event >::event, and TimedEvent< Event >::time.